---
dontChroot: false
timeout: 30
verbose: true
script:
  - "/usr/local/sbin/ailinux-installed-cleanup ${USER}"

i18n:
  name: "Live-System-Dateien entfernen"
  name[de]: "Live-System-Dateien entfernen"
  name[en]: "Remove live-system files"
