modules-search: [ local, /usr/lib/x86_64-linux-gnu/calamares/modules ]

instances:
  - id:       welcome
    module:   welcome
    config:   welcome.conf
  - id:       partition
    module:   partition
    config:   partition.conf
  - id:       unpackfs
    module:   unpackfs
    config:   unpackfs.conf
  - id:       users
    module:   users
    config:   users.conf
  - id:       finished
    module:   finished
    config:   finished.conf
  - id:       cleanup
    module:   shellprocess
    config:   cleanup.conf

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - services-systemd
    - initramfscfg
    - initramfs
    - grubcfg
    - bootloader
    - packages
    - cleanup
    - umount
  - show:
    - finished

branding: ailinux
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
quit-at-end: false
