#!/bin/sh
set -eu

project_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
packages_url=${AILINUX_KERNEL_PACKAGES_URL:-"https://repo.ailinux.me/mirror/repo.ailinux.me/dists/resolute/main/binary-amd64/Packages.gz"}
out_file="$project_dir/config/ailinux-kernel.env"

for tool in curl gzip awk dpkg mktemp; do
    command -v "$tool" >/dev/null 2>&1 || {
        echo "Missing kernel resolver dependency: $tool" >&2
        exit 1
    }
done

tmp_dir=$(mktemp -d)
trap 'rm -rf "$tmp_dir"' EXIT HUP INT TERM

curl -fsSL --retry 3 --connect-timeout 15 "$packages_url" -o "$tmp_dir/Packages.gz"
gzip -dc "$tmp_dir/Packages.gz" | awk '
    BEGIN { RS=""; FS="\n" }
    {
        package=""; version=""
        for (i=1; i<=NF; i++) {
            if ($i ~ /^Package: /) package=substr($i, 10)
            if ($i ~ /^Version: /) version=substr($i, 10)
        }
        if (package ~ /^linux-image-.*-ailinux$/ && index(package, "-dbg") == 0 && version != "")
            print package "\t" version
    }
' > "$tmp_dir/candidates"

test -s "$tmp_dir/candidates" || {
    echo "No installable AILinuX kernel package found in $packages_url" >&2
    exit 1
}

latest_package=
latest_version=
tab=$(printf '\t')
while IFS="$tab" read -r package version; do
    if [ -z "$latest_version" ] || dpkg --compare-versions "$version" gt "$latest_version"; then
        latest_package=$package
        latest_version=$version
    fi
done < "$tmp_dir/candidates"

latest_flavour=${latest_package#linux-image-}
tmp_out="$out_file.tmp.$$"
cat > "$tmp_out" <<EOF
# Generated by scripts/resolve-latest-kernel.sh
AILINUX_KERNEL_PACKAGE='$latest_package'
AILINUX_KERNEL_FLAVOUR='$latest_flavour'
AILINUX_KERNEL_VERSION='$latest_version'
EOF
chmod 0644 "$tmp_out"
mv "$tmp_out" "$out_file"

echo "Latest AILinuX kernel: $latest_package ($latest_version)"
